### PR TITLE
Update ru.js

### PR DESCRIPTION
**Pull request by jensaymoo**

### CODE REVIEW

**Comment by nursoda** [comment]
Hi @jensaymoo When reviewing the [french translation](https://github.com/nursoda/twofactor_email/pull/343/files#diff-ab97a56738913a50d2334c4d3f10991748d3e29d011f5a674734b63d33d5ce9e), I noticed that [info.xml](https://github.com/nursoda/twofactor_email/blob/main/appinfo/info.xml) lacks a russian translation for the `<summary>` field. Could you please provide it (as reply to this message or as separate PR):

```
<summary lang="en">Two-Factor Email Provider</summary>
```

Or would you advise not to translate it?

**Comment by nursoda** [comment]
THAT was quick, THANKS :))

**Comment by nursoda** [comment]
But…I see changes in ru.js, but no info.xml!?

**Comment by jensaymoo** [comment]
See new PR, https://github.com/nursoda/twofactor_email/pull/344

**Pull request merged**
